#!/usr/bin/bash

curl -O -s http://pilot.circonus.com/joyent/5.11/ea.pkgs
while read pkgs
do
	PKG=`echo $pkgs | awk '{print $1;}'`
	VERS=`echo $pkgs | awk '{print $2;}'`
	FILE=`echo $pkgs | awk '{print $3;}'`
	if [ ! -f $PKG.$VERS.tgz ]; then
		./pkg5-pkgsrc $FILE $PKG
		mv $PKG.tgz $PKG.$VERS.tgz
	fi
  ln -sf $PKG.$VERS.tgz $PKG.tgz
done < ea.pkgs
