#!/bin/sh

case `uname` in
	SunOS)
		if [ -n "`grep OmniOS /etc/release`" ]; then
			/opt/napp/bin/omnios-canupdate.sh
		elif [ -x /opt/local/sbin/pkg_add ]; then
			/opt/napp/bin/smartos-canupdate.sh
		else
			/opt/napp/bin/sol11-canupdate.sh
		fi
		;;

	*)	yum check-update -q | grep .
		;;
esac

