#!/bin/sh

# no args returns current configuration for eth0
# single arg "dhcp" sets it to dhcp and waits for dhcp, prints out results
# 3 args (ip, netmask, gateway) sets it to static, prints out results

IPADDR=$1
NETMASK=$2
GATEWAY=$3
DEVICE=eth0
ONBOOT=yes
CONFIG=/etc/sysconfig/network-scripts/ifcfg-$DEVICE

current() {
  BOOTPROTO=`awk -F= '/^BOOTPROTO=/{print $2;}' < $CONFIG`
  IP=`ip addr show dev eth0 scope global | awk '/^ +inet/{print $2" "$4}'`
  echo "$BOOTPROTO $IP"
}
if [ "$IPADDR"X == "X" ]; then
	current
	exit 0
else
	if [ "$IPADDR" == "dhcp" ]; then
		echo "DEVICE=$DEVICE" > $CONFIG
		echo "ONBOOT=$ONBOOT" >> $CONFIG
		echo "BOOTPROTO=dhcp" >> $CONFIG
		ifdown $DEVICE && ifup $DEVICE
                current
		exit 0
	fi
	if [ "$NETMASK"X == "X" ]; then
		echo "need netmask and gateway"
		exit 1
	fi
	if [ "$GATEWAY"X == "X" ]; then
		echo "need gateway"
		exit 1
	fi
	echo "DEVICE=$DEVICE" > $CONFIG
	echo "ONBOOT=$ONBOOT" >> $CONFIG
	echo "BOOTPROTO=static" >> $CONFIG
	echo "IPADDR=$IPADDR" >> $CONFIG
	echo "NETMASK=$NETMASK" >> $CONFIG
	echo "GATEWAY=$GATEWAY" >> $CONFIG
	ifdown $DEVICE && ifup $DEVICE
        current
	exit 0
fi

